apiVersion: apps/v1
kind: Deployment
metadata:
  name: qkc-con-brd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qkc-con-brd
  template:
    metadata:
      labels:
        app: qkc-con-brd
    spec:
      containers:
      - name: qkc-con-brd
        image: minho7336/bro-con:1.4
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: [BOOTSTRAP IP]
        - name: KAFKA_CONSUMER_TOPIC
          value: "qkc-top-brd"
        - name: KAFKA_PRODUCER_TOPIC_SIM
          value: "qkc-top-sim"
        - name: KAFKA_PRODUCER_TOPIC_REV
          value: "qkc-top-rev"
        - name: KAFKA_GROUP_ID
          value: "qkc"
        - name: MONGO_COLLECTION_NAME
          value: "broadcast"
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: qkc-db-cnf
              key: AWS_REGION
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: qkc-aws-scr
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: qkc-aws-scr
              key: aws-secret-access-key
        - name: S3_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: qkc-db-cnf
              key: S3_BUCKET_NAME
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: qkc-db-cnf
              key: MONGO_URI
        - name: MONGO_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: qkc-db-cnf
              key: MONGO_DB_NAME
