apiVersion: batch/v1
kind: CronJob
metadata:
  name: qkc-crj-gss
spec:
  schedule: "0 14 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-container
            image: minho7336/gsshop_cronjob:latest
            env:
            - name: bootstrap_servers
              valueFrom:
                configMapKeyRef:
                  name: qkc-crj-cnf
                  key: bootstrap_servers
            - name: topic
              valueFrom:
                configMapKeyRef:
                  name: qkc-crj-cnf
                  key: topic
            command: ["/entrypoint_gsshop.sh"]
          restartPolicy: OnFailure
