apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: qkc-app-bck
  name: qkc-app-bck
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qkc-app-bck
  template:
    metadata:
      labels:
        app: qkc-app-bck
    spec:
      containers:
      - image: crystal119/backend:1.3
        name: backend
        ports:
        - containerPort: 8000
        resources: {}
        env:
        - name: MONGO_IP
          value: "192.168.0.6"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_DB_NAME
          value: "quickcatch"
        - name: MONGO_USER
          value: "quickcatch"
        - name: MONGO_PASSWORD
          value: "pass123"

status: {}
