apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: qkc-app-bck
  name: qkc-svc-bck
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: qkc-app-bck
  type: NodePort
status:
  loadBalancer: {}
