apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: qkc-app-fro
  name: qkc-app-fro
  namespace: qkc-nsp-fro
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qkc-app-fro
  template:
    metadata:
      labels:
        app: qkc-app-fro
    spec:
      containers:
      - image: minho7336/qkc-app-fro:1.0
        name: quickcatch
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_ADDR
          value: "192.168.0.10"
        - name: BACKEND_PORT
          value: "30974"
